### ISSUE TITLE
Error when accessing Top Sums 

### ISSUE THREAD

**Issue by oliverde8** [eXpansionPluginPack/eXpansion#150]
#0 /libraries/ManiaLivePlugins/eXpansion/Core/types/ErrorHandler.php(15): ManiaLive\Application\ErrorHandling::createExceptionFromError(8, 'Undefined prope...', '/home/creative/...', 47)
#1 /libraries/ManiaLivePlugins/eXpansion/LocalRecords/Gui/Controls/TopsumItem.php(47): ManiaLivePlugins\eXpansion\Core\types\ErrorHandler::createExceptionFromError(8, 'Undefined prope...', '/home/creative/...', 47, Array)
#2 /libraries/ManiaLivePlugins/eXpansion/LocalRecords/Gui/Windows/TopSumsWindow.php(48): ManiaLivePlugins\eXpansion\LocalRecords\Gui\Controls\TopsumItem->__construct(9, 'eugeneinthesky', Object(stdClass), 100)
#3 /libraries/ManiaLivePlugins/eXpansion/LocalRecords/LocalBase.php(1240): ManiaLivePlugins\eXpansion\LocalRecords\Gui\Windows\TopSumsWindow->setDatas(Array)
#4 [internal function]: ManiaLivePlugins\eXpansion\LocalRecords\LocalBase->showTopSums('krestoff', '\ManiaLivePlugi...')
#5 /vendor/maniaplanet/manialive-lib/ManiaLive/PluginHandler/PluginHandler.php(195): ReflectionMethod->invokeArgs(Object(ManiaLivePlugins\eXpansion\LocalRecords\LocalRecords), Array)
#6 /vendor/maniaplanet/manialive-lib/ManiaLive/PluginHandler/Plugin.php(162): ManiaLive\PluginHandler\PluginHandler->callPublicMethod(Object(ManiaLivePlugins\eXpansion\Menu\Menu), '\ManiaLivePlugi...', 'showTopSums', Array)
#7 /libraries/ManiaLivePlugins/eXpansion/Menu/Menu.php(169): ManiaLive\PluginHandler\Plugin->callPublicMethod('\ManiaLivePlugi...', 'showTopSums', 'krestoff')
#8 [internal function]: ManiaLivePlugins\eXpansion\Menu\Menu->actions('krestoff', 'topsums', Array)
#9 /exp/vendor/maniaplanet/manialive-lib/ManiaLive/Gui/ActionHandler.php(71): call_user_func_array(Array, Array)
#10 /vendor/maniaplanet/manialive-lib/ManiaLive/DedicatedApi/Callback/Event.php(66): ManiaLive\Gui\ActionHandler->onPlayerManialinkPageAnswer(197, 'krestoff', '30', Array)
#11 /vendor/maniaplanet/manialive-lib/ManiaLive/Event/Dispatcher.php(132): ManiaLive\DedicatedApi\Callback\Event->fireDo(Object(ManiaLive\Gui\ActionHandler))
#12 /vendor/maniaplanet/manialive-lib/ManiaLive/Application/Application.php(123): ManiaLive\Event\Dispatcher::dispatch(Object(ManiaLive\DedicatedApi\Callback\Event))
#13 /bootstrapperded.php(73): ManiaLive\Application\Application->run()
#14 {main}

**Comment by oliverde8** [comment]
!! Still need fixing I just removed the line with the error.
