### ISSUE TITLE
AutoQueue: trying to force when there are no player slots available

### ISSUE THREAD

**Issue by tomvlk** [eXpansionPluginPack/eXpansion#152]
As showing in logs, several of this exceptions came by:

```
[2015-02-15T21:46:58+01:00] 
    Occured on 15.02.2015 at 21:46:58 at process with ID #10221
    ---------------------------------
 -> Maniaplanet\DedicatedServer\Xmlrpc\ServerOptionsException with code -1000
    There are too many players
  - in /path/to/eXpansion/vendor/maniaplanet/dedicated-server-api/libraries/Maniaplanet/DedicatedServer/Xmlrpc/FaultException.php on line 75
  - Stack: #0 /path/to/eXpansion/vendor/maniaplanet/dedicated-server-api/libraries/Maniaplanet/DedicatedServer/Xmlrpc/GbxRemote.php(205): Maniaplanet\DedicatedServer\Xmlrpc\FaultException::create('There are too m...', -1000)
           #1 /path/to/eXpansion/vendor/maniaplanet/dedicated-server-api/libraries/Maniaplanet/DedicatedServer/Xmlrpc/GbxRemote.php(130): Maniaplanet\DedicatedServer\Xmlrpc\GbxRemote->flush(true)
           #2 /path/to/eXpansion/vendor/maniaplanet/dedicated-server-api/libraries/Maniaplanet/DedicatedServer/Connection.php(153): Maniaplanet\DedicatedServer\Xmlrpc\GbxRemote->query('ForceSpectator', Array)
           #3 /path/to/eXpansion/vendor/maniaplanet/dedicated-server-api/libraries/Maniaplanet/DedicatedServer/Connection.php(4008): Maniaplanet\DedicatedServer\Connection->execute('ForceSpectator', Array, false)
           #4 /path/to/eXpansion/libraries/ManiaLivePlugins/eXpansion/AutoQueue/AutoQueue.php(135): Maniaplanet\DedicatedServer\Connection->forceSpectator('sorrowcroatia19...', 2)
           #5 /path/to/eXpansion/libraries/ManiaLivePlugins/eXpansion/AutoQueue/AutoQueue.php(127): ManiaLivePlugins\eXpansion\AutoQueue\AutoQueue->queueReleaseNext()
           #6 /path/to/eXpansion/libraries/ManiaLivePlugins/eXpansion/AutoQueue/AutoQueue.php(120): ManiaLivePlugins\eXpansion\AutoQueue\AutoQueue->queRealeseAvailable()
           #7 /path/to/eXpansion/vendor/maniaplanet/manialive-lib/ManiaLive/DedicatedApi/Callback/Event.php(86): ManiaLivePlugins\eXpansion\AutoQueue\AutoQueue->onBeginRound()
           #8 /path/to/eXpansion/vendor/maniaplanet/manialive-lib/ManiaLive/Event/Dispatcher.php(132): ManiaLive\DedicatedApi\Callback\Event->fireDo(Object(ManiaLivePlugins\eXpansion\AutoQueue\AutoQueue))
           #9 /path/to/eXpansion/vendor/maniaplanet/manialive-lib/ManiaLive/Application/Application.php(123): ManiaLive\Event\Dispatcher::dispatch(Object(ManiaLive\DedicatedApi\Callback\Event))
           #10 /path/to/eXpansion/bootstrapper.php(73): ManiaLive\Application\Application->run()
           #11 {main}

```

**Comment by oliverde8** [comment]
Thanks, we will check

**Comment by tomvlk** [comment]
Maybe relative information:
Server running in scripted mode, script: Chase.Script.txt.
