### ISSUE TITLE
Dedimania script crash

### ISSUE THREAD

**Issue by oliverde8** [eXpansionPluginPack/eXpansion#153]
```
[2015-02-18T23:58:54+01:00] 
    Occured on 18.02.2015 at 23:58:54 at process with ID #4567
    ---------------------------------
-> ErrorException with code 8
    Undefined index: PLAYERLOGIN
  - in /ManiaLive/libraries/ManiaLivePlugins/eXpansion/Dedimania_Script/Dedimania_Script.php on line 67
  - Stack: #0 /ManiaLive/libraries/ManiaLivePlugins/eXpansion/Core/types/ErrorHandler.php(15): ManiaLive\Application\ErrorHandling::createExceptionFromError(8, 'Undefined index...', '/Ma...', 67)

#1 /ManiaLive/libraries/ManiaLivePlugins/eXpansion/Dedimania_Script/Dedimania_Script.php(67): ManiaLivePlugins\eXpansion\Core\types\ErrorHandler::createExceptionFromError(8, 'Undefined index...', /Ma...', 67, Array)

#2 [internal function]: ManiaLivePlugins\eXpansion\Dedimania_Script\Dedimania_Script->LibXmlRpc_OnWayPoint('PLAYERLOGIN', '#1705254', 36718, 6, true, 36718, 6, true)

#3 /ManiaLive/libraries/ManiaLivePlugins/eXpansion/Core/types/BasicPlugin.php(300): call_user_func_array(Array, Array)

#4 /ManiaLive/vendor/maniaplanet/manialive-lib/ManiaLive/DedicatedApi/Callback/Event.php(98): ManiaLivePlugins\eXpansion\Core\types\BasicPlugin->onModeScriptCallback('LibXmlRpc_OnWay...', Array)

#5 /ManiaLive/vendor/maniaplanet/manialive-lib/ManiaLive/Event/Dispatcher.php(132): ManiaLive\DedicatedApi\Callback\Event->fireDo(Object(ManiaLivePlugins\eXpansion\Dedimania_Script\Dedimania_Script))

#6 /ManiaLive/vendor/maniaplanet/manialive-lib/ManiaLive/Application/Application.php(123): ManiaLive\Event\Dispatcher::dispatch(Object(ManiaLive\DedicatedApi\Callback\Event))

#7 /ManiaLive/bootstrapper.php(73): ManiaLive\Application\Application->run()

#8 {main}
```

**Comment by oliverde8** [comment]
Othere error

```
[2015-02-20T18:42:58+01:00] 
    Occured on 20.02.2015 at 18:42:58 at process with ID #15820
    ---------------------------------
-> ErrorException with code 2
    array_key_exists(): The first argument should be either a string or an integer
  - in /gameserver/maniaplanet/greenwhitenadeo/expansion/libraries/ManiaLivePlugins/eXpansion/Dedimania_Script/Dedimania_Script.php on line 54
  - Stack: #0 /gameserver/maniaplanet/greenwhitenadeo/expansion/libraries/ManiaLivePlugins/eXpansion/Core/types/ErrorHandler.php(15): ManiaLive\Application\ErrorHandling::createExceptionFromError(2, 'array_key_exist...', '/gameserver/man...', 54)
           #1 [internal function]: ManiaLivePlugins\eXpansion\Core\types\ErrorHandler::createExceptionFromError(2, 'array_key_exist...', '/gameserver/man...', 54, Array)
           #2 /gameserver/maniaplanet/greenwhitenadeo/expansion/libraries/ManiaLivePlugins/eXpansion/Dedimania_Script/Dedimania_Script.php(54): array_key_exists(7898, Array)
           #3 [internal function]: ManiaLivePlugins\eXpansion\Dedimania_Script\Dedimania_Script->LibXmlRpc_OnWayPoint(7898, '#68637', 26648, 2, true, 26648, 2, true)
           #4 /gameserver/maniaplanet/greenwhitenadeo/expansion/libraries/ManiaLivePlugins/eXpansion/Core/types/BasicPlugin.php(300): call_user_func_array(Array, Array)
           #5 /gameserver/maniaplanet/greenwhitenadeo/expansion/vendor/maniaplanet/manialive-lib/ManiaLive/DedicatedApi/Callback/Event.php(98): ManiaLivePlugins\eXpansion\Core\types\BasicPlugin->onModeScriptCallback('LibXmlRpc_OnWay...', Array)
           #6 /gameserver/maniaplanet/greenwhitenadeo/expansion/vendor/maniaplanet/manialive-lib/ManiaLive/Event/Dispatcher.php(132): ManiaLive\DedicatedApi\Callback\Event->fireDo(Object(ManiaLivePlugins\eXpansion\Dedimania_Script\Dedimania_Script))
           #7 /gameserver/maniaplanet/greenwhitenadeo/expansion/vendor/maniaplanet/manialive-lib/ManiaLive/Application/Application.php(123): ManiaLive\Event\Dispatcher::dispatch(Object(ManiaLive\DedicatedApi\Callback\Event))
           #8 /gameserver/maniaplanet/greenwhitenadeo/expansion/bootstrapper.php(73): ManiaLive\Application\Application->run()
           #9 {main}
```

**Comment by oliverde8** [comment]
Error was identified with a login that is actually composed only of numbers, should be fixed.
